easy_admin:
    site_name: 'Advertisement manager'
    entities:
        YouRentaUser:
            class: App\Entity\YouRenta\YouRentaUser
            label: YouRenta users
            new:
                fields: ['login', 'password']
            edit:
                fields: ['login', 'password']
            list:
                fields: ['id', 'login', 'password']
        YouRentaAdvertisement:
            class: App\Entity\YouRenta\YouRentaAdvertisement
            label: YouRenta advertisements
    
