easy_admin:
    site_name: 'Advertisement manager'
    entities:
        YouRentaUser:
            class: App\Entity\YouRenta\YouRentaUser
            label: 'YouRenta users'
        YouRentaAdvertisement:
            class: App\Entity\YouRenta\YouRentaAdvertisement
            label: 'YouRenta advertisements'
    
