easy_admin:
    site_name: 'Advertisement manager'
    entities:
        YouRentaUser:
            class: App\Entity\YouRenta\YouRentaUser
            label: YouRenta users
            form:
                fields:
                    - login
                    - password
            list:
                fields:
                    - id
                    - login
                    - password
        YouRentaAdvertisement:
            class: App\Entity\YouRenta\YouRentaAdvertisement
            label: YouRenta advertisements
            list:
                fields:
                    - city
                    - street
                    - buildingNumber
                    - roomsNumber
            form:
                fields:
                    - objectType
                    - city
                    - district
                    - street
                    - buildingNumber
                    - roomsNumber
                    - priceDay
                    - priceNight
                    - priceHour
                    - priceWedding
                    - guestCount
                    - floor
                    - floorsCount
                    - totalArea
                    - firstPhone
                    - secondPhone
                    - internet
                    - conditioner
                    - washer
                    - parking
                    - description
                    - rentConditions
                    - rentConditions
                    - rentConditionsWedding
                    - youTube
                    - { property: 'photos', type: 'collection', type_options: {entry_type: App\Form\YouRentaAdvertisementPhotoType, by_reference: false}}
                    - user
    
