easy_admin:
    site_name: Advertisement manager
    entities:
        YouRentaUser:
            class: App\Entity\YouRenta\YouRentaUser
            label: YouRenta users
            form:
                fields:
                    - { property: login, type: email}
                    - { property: password, type: password}
            list:
                fields:
                    - id
                    - login
                    - password
        YouRentaAdvertisement:
            class: App\Entity\YouRenta\YouRentaAdvertisement
            label: YouRenta advertisements
            list:
                fields:
                    - city
                    - street
                    - buildingNumber
                    - roomsNumber
                    - user
            form:
                fields:
                    - objectType
                    - city
                    - district
                    - street
                    - buildingNumber
                    - { property: roomsNumber, type: choice, type_options: {choices: {1: 1, 2: 2, 3: 3, 4: 4}}}
                    - { property: priceDay, type: money, type_options: {currency: RUB}}
                    - { property: priceNight, type: money, type_options: {currency: RUB}}
                    - { property: priceHour, type: money, type_options: {currency: RUB}}
                    - { property: priceWedding, type: money, type_options: {currency: RUB}}
                    - guestCount
                    - floor
                    - floorsCount
                    - totalArea
                    - { property: firstPhone, type: tel}
                    - { property: secondPhone, type: tel}
                    - internet
                    - conditioner
                    - washer
                    - parking
                    - description
                    - rentConditions
                    - rentConditions
                    - rentConditionsWedding
                    - youTube
                    - { property: photos, type: collection, type_options: {entry_type: App\Form\YouRentaAdvertisementPhotoType, by_reference: false}}
                    - user
    
