vich_uploader:
    db_driver: orm
    mappings:
        yourenta_advertisement_images:
            uri_prefix: '%app.path.yourenta_advertisement_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.yourenta_advertisement_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
